osx_image: xcode10
language: objective-c
script:
- sudo gem install cocoapods -v 1.5.3
- travis_retry pod repo update > /dev/null
- pod lib lint --use-libraries --allow-warnings || pod lib lint --allow-warnings
- carthage update
- carthage build --no-skip-current && carthage archive
- xcodebuild -project mParticle-CleverTap.xcodeproj -scheme mParticle_CleverTapTests -destination 'platform=iOS Simulator,OS=12.0,name=iPhone XS' test
